python coteaching_main.py --dataset mri --noise_type symmetric --noise_rate 0.1
python coteaching_main.py --dataset mri --noise_type pairflip --noise_rate 0.1
python coteaching_main.py --dataset mri --noise_type symmetric --noise_rate 0.2
python coteaching_main.py --dataset mri --noise_type pairflip --noise_rate 0.2
python coteaching_main.py --dataset mri --noise_type symmetric --noise_rate 0.3
python coteaching_main.py --dataset mri --noise_type pairflip --noise_rate 0.3
python coteaching_main.py --dataset mri --noise_type symmetric --noise_rate 0.4
python coteaching_main.py --dataset mri --noise_type pairflip --noise_rate 0.4
python coteaching_main.py --dataset mri --noise_type symmetric --noise_rate 0.5
python coteaching_main.py --dataset mri --noise_type pairflip --noise_rate 0.5
python coteaching_main.py --dataset mri --noise_type symmetric --noise_rate 0.6
python coteaching_main.py --dataset mri --noise_type pairflip --noise_rate 0.6
python coteaching_main.py --dataset mri --noise_type symmetric --noise_rate 0.7
python coteaching_main.py --dataset mri --noise_type pairflip --noise_rate 0.7
python coteaching_main.py --dataset mri --noise_type symmetric --noise_rate 0.8
python coteaching_main.py --dataset mri --noise_type pairflip --noise_rate 0.8
python coteaching_main.py --dataset mri --noise_type symmetric --noise_rate 0.9
python coteaching_main.py --dataset mri --noise_type pairflip --noise_rate 0.9